formatting

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -75,48 +75,48 @@ jobs: # a collection of steps
     steps:
       - checkout
       - run:
-        name: Cut new release
-        command: |
-          # assemble current and new version numbers
-          OLD_VERSION=$(mvn -s .circleci/settings.xml -q \
-            -Dexec.executable="echo" -Dexec.args='${project.version}' \
-            --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
-          NEW_VERSION="${OLD_VERSION/-SNAPSHOT/}"
-          echo "Releasing $OLD_VERSION as $NEW_VERSION"
-
-          # ensure dependencies use release versions
-          mvn -s .circleci/settings.xml versions:use-releases
-
-          # write release version to POM
-          mvn -s .circleci/settings.xml versions:set -DnewVersion="$NEW_VERSION"
-
-          # setup git
-          git config user.name "Release Script"
-          git config user.email "builds@understoryweather.com"
-
-          # commit and tag
-          git add pom.xml
-          git commit -m "release: $NEW_VERSION"
-          git tag "$NEW_VERSION"
-
-          # land on master and publish
-          git checkout master
-          git merge --no-edit release
-          git push origin master --tags
-
-          # increment minor version number
-          MAJ_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 1)
-          MIN_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 2)
-          NEW_MINOR=$(($MIN_VERSION + 1))
-          DEV_VERSION="$MAJ_VERSION.$NEW_MINOR-SNAPSHOT"
-
-          # ready development branch
-          git checkout verify
-          git merge --no-edit release
-          mvn -s .circleci/settings.xml versions:set -DnewVersion="$DEV_VERSION"
-          git add pom.xml
-          git commit -m "ready for development: $DEV_VERSION"
-          git push origin verify
-
-          # clean up release branch
-          git push origin :release
+          name: Cut new release
+          command: |
+            # assemble current and new version numbers
+            OLD_VERSION=$(mvn -s .circleci/settings.xml -q \
+              -Dexec.executable="echo" -Dexec.args='${project.version}' \
+              --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
+            NEW_VERSION="${OLD_VERSION/-SNAPSHOT/}"
+            echo "Releasing $OLD_VERSION as $NEW_VERSION"
+    
+            # ensure dependencies use release versions
+            mvn -s .circleci/settings.xml versions:use-releases
+    
+            # write release version to POM
+            mvn -s .circleci/settings.xml versions:set -DnewVersion="$NEW_VERSION"
+    
+            # setup git
+            git config user.name "Release Script"
+            git config user.email "builds@understoryweather.com"
+    
+            # commit and tag
+            git add pom.xml
+            git commit -m "release: $NEW_VERSION"
+            git tag "$NEW_VERSION"
+    
+            # land on master and publish
+            git checkout master
+            git merge --no-edit release
+            git push origin master --tags
+    
+            # increment minor version number
+            MAJ_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 1)
+            MIN_VERSION=$(echo "$NEW_VERSION" | cut -d '.' -f 2)
+            NEW_MINOR=$(($MIN_VERSION + 1))
+            DEV_VERSION="$MAJ_VERSION.$NEW_MINOR-SNAPSHOT"
+    
+            # ready development branch
+            git checkout verify
+            git merge --no-edit release
+            mvn -s .circleci/settings.xml versions:set -DnewVersion="$DEV_VERSION"
+            git add pom.xml
+            git commit -m "ready for development: $DEV_VERSION"
+            git push origin verify
+    
+            # clean up release branch
+            git push origin :release
